spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  jackson:
    time-zone: Asia/Kolkata

auth:
  jwt:
    private-key: ${AUTH_JWT_PRIVATE_KEY}
  verification:
    hmac-secret: ${AUTH_VERIFICATION_HMAC_SECRET}
  client-id: ${AUTH_CLIENT_ID}